name: template-build

on:
  workflow_call:
    # Map the job outputs to workflow outputs
    outputs:
      fullSemVer: 
        description: "The full semantic version"
        value: ${{ jobs.template-build.outputs.fullSemVer }}

jobs:
  template-build:
    runs-on: ubuntu-latest

    # Map step output to a job output
    outputs:
      fullSemVer: ${{ steps.cake.outputs.FullSemVer }}

    steps:
      - name: Get the sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Cake script
        id: cake
        uses: cake-build/cake-action@5167c3f6a9e15c76f009de2acdfb9488552bc0b9 # v3
        with:
          project-path: build/Build.csproj
